builds:
  - binary: shuffle-files
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED = 0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: shuffle-files
    folder: Formula
    homepage: https://dotoca.net/shuffle-files/
    description: "This is a CLI tool which shuffles the files in the directory"
    repository:
      owner: xvoland
      name: shuffle-files
    commit_author:
      name: Vitalii Tereshchuk
      email: xvoland@dotoca.net

checksum:
  name_template: 'checksums.txt'